### ISSUE TITLE
Bug: Favourite and Boost icon moves

### ISSUE THREAD

**Issue by peijun-dev** [halcyon-suite/halcyon-for-mastodon#11]
フェイバリット機能を利用したときに星形のユニットが左に動いてしまう問題がある。
![484ea950-4901-41d2-a37a-acb2d74d4db2](https://cloud.githubusercontent.com/assets/27123488/26791975/d2b7330c-4a53-11e7-9166-75cb9db3850e.png)

**Comment by NeetShin** [comment]
Changed to like this. thx for feedback.
<img width="588" alt="2017-06-07 14 38 52" src="https://user-images.githubusercontent.com/19276905/26871173-e8ce9c7e-4b8f-11e7-9611-2ca2272e4d36.png">
