### ISSUE TITLE
レスポンシブウェブデザイン に対応してほしい

### ISSUE THREAD

**Issue by 39e** [halcyon-suite/halcyon-for-mastodon#2]
タブレットで開いたときに文字がずれたり表示がずれます。
またPCのブラウザでも幅が充分ではないときに表示が崩れるので修正してほしいです。

![image](https://cloud.githubusercontent.com/assets/15976255/26680604/11e23e4c-4715-11e7-9113-b2ecabd646b3.png)

**Comment by NeetShin** [comment]
ご報告ありがとうございます。確かにそのようであったため、1235px以上であるか否かでメディアクエリを用いて横幅などを変更しました。

![2017-06-03 17 30 48](https://cloud.githubusercontent.com/assets/19276905/26753375/7b497382-4882-11e7-884d-67418d4eece4.jpg)

これによってディスプレイ横幅が900pxのものから1234pxまでのデザインがカバーされましたが、900px以下のディスプレイに関しては現状サポートに別途スクリプトなどを用意する必要があることから見送らせていただきました。また何かございましたらご報告頂けると幸いです。

**Comment by 39e** [comment]
タブレットでも表示が崩れないことを確認しました。

> 900px以下のディスプレイ

わかりました。もし対応してくれるのであれば待ってます!
