### ISSUE TITLE
 Suggestions for setup.

### ISSUE THREAD

**Issue by 39e** [halcyon-suite/halcyon-for-mastodon#8]
[セットアップ](https://github.com/halcyon-suite/halcyon-for-mastodon/blob/4630548654a17484485a785c4e63bfb3e74a9cb0/README.md#setup仮) についてですが `/authorize/Mastodon.php` で設定してる値を `.env` で設定するようにしてみてはいかがですか？

(ほんとは私がプルリクを送れればいいのですが、PHPに関する知識が乏しく何もできなくてすみません)

**Comment by NeetShin** [comment]
ご提案ありがとうございます、やっぱり直書きはやめたほうが良かったですね。
しかし、PHPで`.env`ファイルを扱うにはどうやら別途ライブラリが必要だったようで、代わりに標準関数が用意されている`.ini`ファイル`/config.ini`を読み込むようにし、README.mdにもそのように加筆しました。
